heroesofddd_rails_application/config/routes.rb
Rails.application.routes.draw do
  mount RailsEventStore::Browser => "/res" if Rails.env.development?
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Defines the root path route ("/")
  # root "posts#index"
  namespace :heroes do
    resources :games, only: [] do
      namespace :creature_recruitment do
        resources :dwellings, only: [ :show ] do
          post "recruit", on: :member
        end
      end
      resource :calendar, only: [] do
        post :next_day, on: :member
      end
    end
  end
end

heroesofddd_rails_application/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

heroesofddd_rails_application/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern

  def event_store
    Rails.configuration.event_store
  end

  def command_bus
    Rails.configuration.command_bus
  end

  def not_found
    render file: "#{Rails.root}/public/404.html", layout: false, status: :not_found
  end
end

heroesofddd_rails_application/app/controllers/heroes/calendars_controller.rb
module Heroes
  class CalendarsController < ApplicationController
    def next_day
      game_id = params[:game_id]
      current_date = Heroes::Calendar::CurrentDateReadModel::State.find_by(game_id: game_id)

      finish_day = Heroes::Calendar::FinishDay.new(current_date.month, current_date.week, current_date.day)
      command_bus.call(finish_day, BuildingBlocks::Application::AppContext.for_game(game_id))

      next_day = calculate_next_day(current_date)
      start_day = Heroes::Calendar::StartDay.new(next_day[:month], next_day[:week], next_day[:day])
      command_bus.call(start_day, BuildingBlocks::Application::AppContext.for_game(game_id))

      @current_date = Heroes::Calendar::CurrentDateReadModel::State.find_by(game_id: game_id)

      respond_to do |format|
        format.turbo_stream { render turbo_stream: turbo_stream.update("current-date", partial: "heroes/calendar/current_date") }
      end
    end

    private

    def calculate_next_day(current_date)
      day = current_date.day + 1
      week = current_date.week
      month = current_date.month

      if day > 7
        day = 1
        week += 1
      end

      if week > 4
        week = 1
        month += 1
      end

      { month: month, week: week, day: day }
    end
  end
end

heroesofddd_rails_application/app/controllers/heroes/creature_recruitment/dwellings_controller.rb
require "heroes/creature_recruitment/read/dwelling_read_model"
require "heroes/calendar/read/current_date_read_model"
require "heroes/creature_recruitment/write/recruit_creature/command_recruit_creature"
require "building_blocks/application/app_context"

# todo: consider last response from here:
# https://claude.ai/chat/a081c14c-26e0-4f92-8371-4e13470cd8c9

module Heroes
  module CreatureRecruitment
    class DwellingsController < ApplicationController
      def show
        game_id = params[:game_id]
        dwelling_id = params[:id]
        @dwelling = DwellingReadModel::State.find_by(game_id: game_id, id: dwelling_id)
        if @dwelling
          @current_date = Heroes::Calendar::CurrentDateReadModel::State.find_by(game_id: game_id)
          render template: "heroes/creature_recruitment/dwellings/index"
        else
          render json: { error: "Dwelling not found" }, status: :not_found
        end
      end

      def recruit
        game_id = params[:game_id]
        dwelling_id = params[:id]
        recruit_count = params[:recruit_count].to_i

        dwelling = DwellingReadModel::State.find_by(game_id: game_id, id: dwelling_id)

        if dwelling
          if recruit_count > 0
            command = Heroes::CreatureRecruitment::RecruitCreature.new(dwelling.id, dwelling.creature_id, recruit_count)

            begin
              command_bus.call(command, BuildingBlocks::Application::AppContext.for_game(game_id))
              dwelling.reload
              message = { type: :notice, text: "Successfully recruited #{recruit_count} #{dwelling.creature_id.pluralize.capitalize}" }
            rescue StandardError => e
              message = { type: :alert, text: "Failed to recruit creatures: #{e.message}" }
            end
          else
            message = { type: :alert, text: "Please select at least one creature to recruit." }
          end
        else
          message = { type: :alert, text: "Dwelling not found" }
        end

        respond_to do |format|
          format.turbo_stream do
            render turbo_stream: turbo_stream.replace(
              "dwelling-#{dwelling_id}",
              partial: "heroes/creature_recruitment/dwellings/dwelling",
              locals: { dwelling: dwelling, message: message }
            )
          end
          format.html { redirect_to heroes_game_creature_recruitment_dwelling_path(game_id, dwelling_id) }
        end
      end
    end
  end
end

heroesofddd_rails_application/app/helpers/application_helper.rb
module ApplicationHelper
end

heroesofddd_rails_application/app/helpers/heroes/creature_recruitment/dwellings_helper.rb
module Heroes
  module CreatureRecruitment
    module DwellingsHelper
      def render_dwelling(dwelling)
        render partial: "heroes/creature_recruitment/dwellings/dwelling", locals: {
          dwelling: dwelling
        }
      end
    end
  end
end

heroesofddd_rails_application/app/views/heroes/astrologers/_week_symbol_modal.html.erb
<div id="week_symbol_modal" class="modal" data-controller="modal">
  <div class="modal__content modal__border">
    <p>Astrologers proclaim week of the <%= week_of.capitalize.gsub("_", " ") %>.</p>
    <p><%= week_of.capitalize.gsub("_", " ") %> growth +<%= growth %></p>
    <p>All dwellings increase population.</p>
    <button data-action="click->modal#close" class="modal__submit-button">
      <%= image_tag "button_submit.png", alt: "Submit" %>
    </button>
  </div>
</div>

heroesofddd_rails_application/app/views/heroes/calendar/_current_date.html.erb
<%= turbo_frame_tag "current-date" do %>
  <div class="current-date">
    <% if @current_date %>
      <p class="current-date__text">Month: <%= @current_date.month %>, Week: <%= @current_date.week %>,
        Day: <%= @current_date.day %></p>
      <%= button_to "Next Day", next_day_heroes_game_calendar_path(@current_date.game_id),
                    method: :post,
                    class: "current-date__next-day-button",
                    data: {
                      disable_with: "Processing..."
                    } %>
    <% end %>
  </div>
<% end %>

heroesofddd_rails_application/app/views/heroes/creature_recruitment/dwellings/_dwelling.html.erb
<div class="recruitment__container"
     id="dwelling-<%= dwelling.id %>"
     data-controller="dwelling"
     data-dwelling-available-creatures-value="<%= dwelling.available_creatures %>"
     data-dwelling-cost-per-troop-value="<%= dwelling.cost_per_troop['resources'].to_json %>"
     data-dwelling-message-value="<%= local_assigns[:message]&.to_json %>">
  <div class="recruitment__border">
    <%= form_with(url: recruit_heroes_game_creature_recruitment_dwelling_path(dwelling.game_id, dwelling), method: :post, id: "recruit-form-#{dwelling.id}", class: "recruitment__component") do |f| %>
      <h1 class="recruitment__title">Recruit <%= dwelling.creature_id.capitalize.pluralize %></h1>
      <%= image_tag "Recruit#{dwelling.creature_id.capitalize}Image.png", alt: "#{dwelling.creature_id.capitalize} image", class: "recruitment__creature-image" %>

      <div class="recruitment__controls">
        <div class="recruitment__cost-per-troop">
          <p class="recruitment__cost-title">Cost Per Troop</p>
          <div class="recruitment__cost-details">
            <% dwelling.cost_per_troop['resources'].each do |resource, amount| %>
              <div class="recruitment__resource">
                <%= image_tag "#{resource.downcase}_resource.png", alt: "#{resource.capitalize} resource", class: "recruitment__resource-image" %>
                <div class="recruitment__resource-amount"><%= amount %></div>
              </div>
            <% end %>
          </div>
        </div>

        <div class="recruitment__center-controls">
          <div class="recruitment__counts">
            <div class="recruitment__count">
              <div class="recruitment__count-title">Available</div>
              <div class="recruitment__count-value"><%= dwelling.available_creatures %></div>
            </div>
            <div class="recruitment__count">
              <div class="recruitment__count-title">Recruit</div>
              <div class="recruitment__count-value" data-dwelling-target="recruitCount">0</div>
            </div>
          </div>
          <div class="recruitment__slider">
            <%= f.range_field :recruit_count,
                              min: 0,
                              max: dwelling.available_creatures,
                              value: 0,
                              class: "recruitment__slider-input",
                              data: {
                                dwelling_target: "slider",
                                action: "input->dwelling#sliderChanged"
                              } %>
          </div>
        </div>

        <div class="recruitment__total-cost" data-dwelling-target="totalCost">
          <p class="recruitment__cost-title">Total Cost</p>
          <div class="recruitment__cost-details">
            <% dwelling.cost_per_troop['resources'].each do |resource, amount| %>
              <div class="recruitment__resource">
                <%= image_tag "#{resource.downcase}_resource.png", alt: "#{resource.capitalize} resource", class: "recruitment__resource-image" %>
                <div class="recruitment__resource-amount" id="total-<%= resource.downcase %>"><%= amount %></div>
              </div>
            <% end %>
          </div>
        </div>
      </div>

      <div class="recruitment__buttons">
        <button type="button" class="recruitment__button recruitment__button--select-all" data-action="click->dwelling#selectAll">
          <%= image_tag "button_select_all.png", alt: "Select All", class: "recruitment__button-image" %>
        </button>
        <%= f.button type: "submit", class: "recruitment__button recruitment__button--recruit" do %>
          <%= image_tag "button_recruit.png", alt: "Recruit", class: "recruitment__button-image" %>
        <% end %>
        <%= link_to heroes_game_creature_recruitment_dwelling_path(dwelling.game_id, dwelling), class: "recruitment__button recruitment__button--cancel" do %>
          <%= image_tag "button_cancel.png", alt: "Cancel", class: "recruitment__button-image" %>
        <% end %>
      </div>
    <% end %>

    <div class="recruitment__message-box">
      <p class="recruitment__message-box__text" data-dwelling-target="messageBox"></p>
    </div>
  </div>
</div>

heroesofddd_rails_application/app/views/heroes/creature_recruitment/dwellings/index.html.erb
<div class="app">
  <%= render_dwelling(@dwelling) %>
  <%= render 'heroes/calendar/current_date' %>
</div>

heroesofddd_rails_application/app/views/heroes/current_date/_current_date.html.erb
<div class="current-date">
  <% if @current_date %>
    <p>Month: <%= @current_date.month %>, Week: <%= @current_date.week %>, Day: <%= @current_date.day %></p>
    <%= button_to "Next Day", heroes_game_calendar_next_day_path(@current_date.game_id), method: :post, class: "next-day-button" %>
<% end %>
</div>

heroesofddd_rails_application/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Heroesofddd Rails Application" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <link rel="manifest" href="/manifest.json">
    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>

    <%= turbo_frame_tag "week_symbol_modal" %>
    <%= turbo_stream_from "week_symbol_modal" %>
  </body>
</html>